import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../static/timeline.js',import.meta.url),'utf8');
const {phaseAt,buildEvents,buildSession}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
for(const [t,g] of [[0,'1'],[59.99,'1'],[60,'1.8'],[81,'1.80'],[82.5,'0.90'],[84,'0'],[105.99,'0'],[106,'0.00'],[107,'0.90'],[108,'1.8'],[131.99,'1.8'],[132,'1'],[172,'1'],[232,'1.8']])assert.equal(phaseAt(t,2).g,g,`phase at ${t}`);
const events=buildEvents(2);
assert.equal(events.length,34);
assert.equal(events[0].time,0);
assert.equal(events[17].time,172);
assert.equal(events[17].speech,'One minute. P 2.');
assert.equal(events.at(-1).time,304);
assert.equal(phaseAt(172,2).parabola,2);
assert.equal(phaseAt(304,2).parabola,2);
assert.ok(events.every((e,i)=>!i||e.time>events[i-1].time));
console.log('Timeline: phase boundaries, event ordering and repeat timing passed.');

assert.equal(events.find(e=>e.label==='30').time,61);
assert.equal(events.find(e=>e.label==='INJECTION').time,81);
for(const t of [81,82.5,83.99,106,107,107.99])assert.equal(phaseAt(t,2).color,'brown');
assert.equal(phaseAt(84,2).color,'yellow');
assert.equal(phaseAt(108,2).color,'red');
const recovery=buildSession(1,true);
assert.equal(recovery.events[0].speech,'Steady flight.');
assert.equal(recovery.events[1].time,40);
assert.equal(recovery.events[1].speech,'One minute. P 1.');
assert.equal(recovery.duration,172);
assert.equal(phaseAt(-40,1).remaining,40);
assert.equal(phaseAt(-0.1,1).color,'green');
assert.equal(phaseAt(0,1).parabola,1);
for(let t=81;t<84;t+=0.1)assert.ok(Number(phaseAt(t+0.05,2).g)<=Number(phaseAt(t,2).g));
for(let t=106;t<107.9;t+=0.1)assert.ok(Number(phaseAt(t+0.05,2).g)>=Number(phaseAt(t,2).g));
console.log('Updated calls, continuous gravity transitions and recovery entry passed.');
